@url_dev=http://localhost:3000/v1/api

#### signup
POST {{url_dev}}/shop/signup
Content-Type: application/json
x-api-key: a036cd5b9b3f19f80d41c63efd8c538c

{
  "name": "Test Shop",
  "email": "shop8@gmail.com",
  "password": "1234qwer"
}