@url_dev=http://localhost:3000/v1/api
@apiKey=cc4932f42a72fc1d812fcd496ea05585
@accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTFkODc2ZTIzNzdhNDhlYTVmZmI2MjciLCJlbWFpbCI6InRyaXZpcDAwMkBnbWFpbC5jb20iLCJpYXQiOjE3NjM1NDI4OTQsImV4cCI6MTc2MzcxNTY5NH0.ssuPbwlSmJAMaN4GbsAXo1Kb7JKcDxIhFaX2GKdEiR8
@clientId=691d876e2377a48ea5ffb627

#### signup
POST {{url_dev}}/shop/signup
Content-Type: application/json
x-api-key: {{apiKey}}

{
  "name": "Admin Shop",
  "email": "trivip002@gmail.com",
  "password": "1234qwer"
}

#### login
POST {{url_dev}}/shop/login
Content-Type: application/json
x-api-key: {{apiKey}}

{
  "email": "trivip002@gmail.com",
  "password": "1234qwer"
}


#### Logout
POST {{url_dev}}/shop/logout
Content-Type: application/json
x-api-key: {{apiKey}}
x-client-id: {{clientId}}
authorization: {{accessToken}}

#### Refresh token
POST {{url_dev}}/shop/refresh-token
Content-Type: application/json
x-api-key: {{apiKey}}
x-client-id: {{clientId}}
x-rtoken-id: {{accessToken}}

