@url_dev=http://localhost:3000/v1/api
@apiKey=cc4932f42a72fc1d812fcd496ea05585
@accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTFkODc2ZTIzNzdhNDhlYTVmZmI2MjciLCJlbWFpbCI6InRyaXZpcDAwMkBnbWFpbC5jb20iLCJpYXQiOjE3NjM5OTM5NTksImV4cCI6MTc2NDE2Njc1OX0.GjILP9JjffTy8lSjE_YA7xuuTpe7QaMWcl4n9FnztCs
@clientId=691d876e2377a48ea5ffb627

#### Create discount
POST {{url_dev}}/discount
Content-Type: application/json
x-api-key: {{apiKey}}
x-client-id: {{clientId}}
authorization: {{accessToken}}

{
  "name": "Summer Sale",
  "description": "20% off on all electronics",
  "type": "percentage",
  "value": 20,
  "max_value": 30000,
  "code": "SUMMER20",
  "start_date": "2025-11-21T00:00:00Z",
  "end_date": "2025-11-30T23:59:59Z",
  "max_uses": 100,
  "uses_count": 0,
  "users_used": [],
  "max_uses_per_user": 1,
  "min_order_value": 200000,
  "created_by": "",
  "is_active": true,
  "applies_to": "specific",
  "product_ids": [
    "691d88282377a48ea5ffb732"
  ]
}

#### Get all discount
GET {{url_dev}}/discount?limit=10&page=1
Content-Type: application/json
x-api-key: {{apiKey}}
x-client-id: {{clientId}}
authorization: {{accessToken}}

### Get discount amount
GET {{url_dev}}/discount/amount
Content-Type: application/json
x-api-key: {{apiKey}}

{
  "codeId": "SUMMER20",
  "userId": "",
  "shopId": "691d876e2377a48ea5ffb627",
  "products": [
    {
      "productId": "691d88282377a48ea5ffb732",
      "quantity": 1,
      "price": 250000
    }
  ]
}

### Get all discount code with product
GET {{url_dev}}/discount/list_product_code?code=SUMMER20&shopId=691d876e2377a48ea5ffb627
Content-Type: application/json
x-api-key: {{apiKey}}

#### Delete discount
DELETE {{url_dev}}/discount/SUMMER20
Content-Type: application/json
x-api-key: {{apiKey}}
x-client-id: {{clientId}}
authorization: {{accessToken}}

### Cancel Discount
POST {{url_dev}}/discount/cancel/SUMMER20
Content-Type: application/json
x-api-key: {{apiKey}}
x-client-id: {{clientId}}
authorization: {{accessToken}}
