@url_dev=https://www.devapihub.com/v1/api
@apiKey=cc4932f42a72fc1d812fcd496ea05585
@accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTFkODc2ZTIzNzdhNDhlYTVmZmI2MjciLCJlbWFpbCI6InRyaXZpcDAwMkBnbWFpbC5jb20iLCJpYXQiOjE3NjM1NDMxNTQsImV4cCI6MTc2MzcxNTk1NH0.zCRs4vAWCA3qgOnkG1xYWeUA4dwXfx1Jx-0xA9lRIK0
@clientId=691d876e2377a48ea5ffb627

#### create product
POST {{url_dev}}/product
Content-Type: application/json
x-api-key: {{apiKey}}
x-client-id: {{clientId}}
authorization: {{accessToken}}

{
  "product_name": "Furniture 20 128GB",
  "product_description": "new Furniture from Apple",
  "product_price": 30,
  "product_shop": "6915c598715f1b732b6b8d07",
  "product_type": "Furniture",
  "product_thumb": "https://example.com/jean.jpg",
  "product_quantity": 5,
  "product_attributes": {
    "brand": "TTF",
    "size": "5 inches",
    "material": "Blue"
  }
}

#### update product
PATCH {{url_dev}}/product/691d5157e7e8c90c4303f4e2
Content-Type: application/json
x-api-key: {{apiKey}}
x-client-id: {{clientId}}
authorization: {{accessToken}}

{
  "product_type": "Furniture",
  "product_attributes": {
    "brand": "Apple",
    "size": "5 inches",
    "material": "Blue"
  }
}

#### delete product
DELETE {{url_dev}}/product/691ab1846f68de6a832695d0
Content-Type: application/json
x-api-key: {{apiKey}}
x-client-id: {{clientId}}
authorization: {{accessToken}}

{
  "product_type": "Electronics"
}


#### Publish product
POST {{url_dev}}/product/publish/691d88282377a48ea5ffb732
Content-Type: application/json
x-api-key: {{apiKey}}
x-client-id: {{clientId}}
authorization: {{accessToken}}

#### UnPublish product
POST {{url_dev}}/product/unpublish/691ab1886f68de6a83269601
Content-Type: application/json
x-api-key: {{apiKey}}
x-client-id: {{clientId}}
authorization: {{accessToken}}

#### Get all draft products
GET {{url_dev}}/product/drafts/all
Content-Type: application/json
x-api-key: {{apiKey}}
x-client-id: {{clientId}}
authorization: {{accessToken}}

#### Get all published products
GET {{url_dev}}/product/published/all
Content-Type: application/json
x-api-key: {{apiKey}}
x-client-id: {{clientId}}
authorization: {{accessToken}}

#### Search products
GET {{url_dev}}/product/search/Swift 14
Content-Type: application/json
x-api-key: a036cd5b9b3f19f80d41c63efd8c538c

### Find all products
GET {{url_dev}}/product
Content-Type: application/json
x-api-key: {{apiKey}}

### Find product
GET {{url_dev}}/product/691d88282377a48ea5ffb732
Content-Type: application/json
x-api-key: {{apiKey}}