@url_dev=http://localhost:3000/v1/api


#### create product
POST {{url_dev}}/product
Content-Type: application/json
x-api-key: a036cd5b9b3f19f80d41c63efd8c538c
x-client-id: 6915c598715f1b732b6b8d07
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTE1YzU5ODcxNWYxYjczMmI2YjhkMDciLCJlbWFpbCI6InNob3BkZXZAZ21haWwuY29tIiwiaWF0IjoxNzYzMjgwNTM5LCJleHAiOjE3NjM0NTMzMzl9.9Aj8WUZxyH5e3Lz4Ozm-uG9qRkkgugXqnQgKnnUYcgE

{
  "product_name": "Furniture 17 128GB",
  "product_description": "new Furniture from Apple",
  "product_price": 70,
  "product_shop": "6915c598715f1b732b6b8d07",
  "product_type": "Furniture",
  "product_thumb": "https://example.com/jean.jpg",
  "product_quantity": 1,
  "product_attributes": {
    "brand": "TTF",
    "size": "17",
    "material": "Black"
  }
}